---

- name: Install ADDS and deploy an AD Domain
  hosts: ad-dc01

  tasks:
    - name: Install ADDS
      ansible.windows.win_feature:
        name: AD-Domain-Services
        state: present
        include_management_tools: yes

    - name: Create folder structure for ADDS
      ansible.windows.win_file:
        path: C:\_adds
        state: directory

    - name: Create an AD forest called ad.aleflab.com
      ansible.windows.win_domain:
        dns_domain_name: ad.aleflab.com
        dns_netbios_name: AD
        install_dns: yes
        create_dns_delegation: no
        forest_mode: WinThreshold
        domain_mode: WinThreshold
        ntds_path: C:\_adds\ntds
        log_path: C:\_adds\logs
        sysvol_path: C:\_adds\sysvol
        safe_mode_password: Password112233

    - name: Reboot the DC
      ansible.windows.win_reboot:

    - name: Set the DNS forwarder to Azure DNS
      ansible.windows.win_powershell:
        script: |
          Set-DnsServerForwarder -IPAddress "168.63.129.16" -UseRootHint $false -Verbose

- name: Deploy the neccessary software on ad-hop01
  hosts: ad-hop01

  tasks:
    - name: Deploy neccessary software using chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name:
          - openssl
          - microsoft-edge
          - wireshark 
          - putty

    - name: Install ADDS RSAT
      ansible.windows.win_feature:
        name: RSAT-AD-Tools
        state: present

- name: Deploy neccessary shortcuts on ad-hop01
  hosts: ad-hop01

  tasks:
    - name: Wireshark
      community.windows.win_shortcut:
        src: 'C:\Program Files\Wireshark\Wireshark.exe'
        dest: 'C:\Users\Public\Desktop\Wireshark.lnk'
        icon: 'C:\Program Files\Wireshark\Wireshark.exe,0'

    - name: Putty
      community.windows.win_shortcut:
        src: 'C:\ProgramData\chocolatey\lib\putty.portable\tools\PUTTY.EXE'
        dest: 'C:\Users\Public\Desktop\Putty.lnk'
        icon: 'C:\ProgramData\chocolatey\lib\putty.portable\tools\PUTTY.EXE,0'
        

- name: Deploy win10pcap on ad-hop01
  hosts: ad-hop01

  tasks:
    - name: Deploy win10pcap using the official MSI
      win_package:
        path: 'http://www.win10pcap.org/download/Win10Pcap-v10.2-5002.msi'
        creates_path: 'C:\Program Files (x86)\Win10Pcap'
        state: present

- name: Join all the hosts to the ad.aleflab.com domain
  hosts:
    - ad-hop01
    - ad-ica01
    - ad-cdp01

  tasks:
    - name: Reboot the computer
      ansible.windows.win_reboot:

    - name: Join AD
      ansible.windows.win_domain_membership:
        state: domain
        dns_domain_name: ad.aleflab.com
        domain_admin_user: ad\maestro
        domain_admin_password: 8CNRA8QTnQ7EExD9MU24g
    
    - name: Reboot the computer
      ansible.windows.win_reboot:

- name: Setup Apache Web Server
  hosts: ad-web01

  tasks:
    - name: Deploy neccessary packages
      ansible.builtin.dnf:
        name:
          - nano
          - httpd
          - mod_ssl
        state: present

    - name: Configure httpd for SSL (1/3)
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: 'ServerName www.example.com\:443'
        line: 'ServerName ad-web01.ad.aleflab.com:443'

    - name: Configure httpd for SSL (2/3)
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: 'SSLCertificateFile'
        line: 'SSLCertificateFile /etc/pki/tls/certs/ad-web01.crt'

    - name: Configure httpd for SSL (3/3)
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf.d/ssl.conf
        regexp: 'SSLCertificateKeyFile'
        line: 'SSLCertificateKeyFile /etc/pki/tls/private/ad-web01.key'
